/* Katalog von Atelier Lehm.
   Eine einzige Quelle für alle Seiten: Raster, Produktseite, Warenkorb und
   Kasse lesen von hier, damit ein Preis nur an einer Stelle steht.
   Schreibweise wie in der Schweiz: ss, nie ß. */

const SHOP = {
  brand: 'Atelier Lehm',
  city: 'Bern',
  shipping: 9,
  freeShippingFrom: 150,
};

const PRODUCTS = [
  {
    id: 'schiefer',
    name: 'Schiefer',
    category: 'Teller',
    price: 124,
    image: 'plates-graphite-pair',
    alt: 'Zwei Teller mit dunkler Schieferglasur auf grauem Leinen',
    lead: 'Zwei Teller, im Holzofen bis fast an die Grenze gebrannt.',
    story: [
      'Die dunkle Glasur entsteht aus Holzasche und Feldspat aus dem Jura. Im Ofen läuft sie über den Rand und zieht sich beim Abkühlen wieder zurück — deshalb trägt jeder Teller eine andere Kante.',
      'Gedacht für Brot, Antipasti und alles, was man in die Mitte des Tisches stellt.',
    ],
    details: ['Steinzeug, im Holzofen gebrannt', 'Ø 24 cm und Ø 21 cm', 'Set zu zwei Tellern', 'Spülmaschinenfest'],
  },
  {
    id: 'knoten',
    name: 'Knoten',
    category: 'Vasen',
    price: 145,
    image: 'vase-sculptural-sand',
    alt: 'Skulpturale Vase aus sandfarbenem Ton mit verschlungener Form',
    lead: 'Eine Vase, die aussieht, als hätte sie sich selbst gefaltet.',
    story: [
      'Von Hand aufgebaut, ohne Drehscheibe. Der Ton wird in Bändern gelegt und so lange bewegt, bis er von selbst stehen bleibt — der Moment davor entscheidet über die Form.',
      'Unglasiert gelassen, damit die Oberfläche das Licht so aufnimmt wie der Sand, aus dem sie kommt.',
    ],
    details: ['Schamottierter Ton, unglasiert', 'Höhe 26 cm', 'Innen versiegelt, wasserdicht', 'Einzelstück'],
  },
  {
    id: 'ascheglasur',
    name: 'Ascheglasur',
    category: 'Becher',
    price: 58,
    image: 'cup-woodfired-speckled',
    alt: 'Becher mit gesprenkelter Ascheglasur in Ocker und Blau',
    lead: 'Vier Tage Holzfeuer, und die Asche legt sich selbst als Glasur.',
    story: [
      'Dieser Becher stand im hinteren Teil des Ofens, dort wo die Flamme am längsten vorbeizieht. Die Sprenkel sind Flugasche, nichts davon ist aufgemalt.',
      'Der Henkel ist bewusst klein: Man hält den Becher mit der ganzen Hand, und im Winter ist das der halbe Sinn der Sache.',
    ],
    details: ['Steinzeug, Anagama-Brand', '2,5 dl', 'Höhe 9 cm', 'Von Hand waschen'],
  },
  {
    id: 'wolkenrand',
    name: 'Wolkenrand',
    category: 'Schalen',
    price: 68,
    image: 'bowl-cream-scalloped',
    alt: 'Cremefarbene Schale mit gewelltem Rand auf hellem Stein',
    lead: 'Der Rand bleibt so, wie ihn die Finger beim Drehen hinterlassen.',
    story: [
      'Solange der Ton noch weich ist, wird der Rand in kurzen Abständen nach aussen gezogen. Zwei Schalen werden dabei nie gleich.',
      'Die matte Glasur ist eine Rezeptur mit Porzellanerde, an der wir seit vier Jahren kaum etwas geändert haben.',
    ],
    details: ['Steinzeug, matt glasiert', 'Ø 18 cm', '6 dl', 'Spülmaschinenfest'],
  },
  {
    id: 'fuchsia',
    name: 'Fuchsia',
    category: 'Becher',
    price: 52,
    image: 'mug-pink-glaze',
    alt: 'Becher mit leuchtend pinker Glasur und grünen Spritzern',
    lead: 'Einmal im Jahr darf im Atelier eine Farbe laut sein.',
    story: [
      'Die Glasur wird im Becher verschüttet statt aufgetragen: Pink zuerst, dann ein Stoss Kupfergrün, und den Rest macht die Schwerkraft.',
      'Kleine Serie, weil sich die Rezeptur nicht zuverlässig wiederholen lässt. Wenn sie weg ist, ist sie weg.',
    ],
    details: ['Steinzeug, glänzend glasiert', '3 dl', 'Höhe 9,5 cm', 'Kleine Serie'],
  },
  {
    id: 'tropfen',
    name: 'Tropfen',
    category: 'Küche',
    price: 96,
    image: 'oil-bottle-cork',
    alt: 'Helle Ölkaraffe mit Korkverschluss und schmalem Ausguss',
    lead: 'Eine Karaffe für Öl, die den letzten Tropfen nicht am Hals hinunterlaufen lässt.',
    story: [
      'Der Ausguss hat uns elf Versuche gekostet. Zu kurz, und das Öl zieht Fäden; zu lang, und die Karaffe sieht aus wie ein Vogel.',
      'Der Korken kommt aus dem Tessin und lässt sich nachbestellen, falls er einmal verloren geht.',
    ],
    details: ['Steinzeug, innen glasiert', '5 dl', 'Korken aus Naturkork', 'Von Hand waschen'],
  },
  {
    id: 'nebelrose',
    name: 'Nebelrose',
    category: 'Kannen',
    price: 210,
    image: 'teapot-mauve',
    alt: 'Teekanne mit mattrosa Glasur, daneben eine Tasse auf einem Teller',
    lead: 'Die Glasur zieht ins Graue, wenn der Himmel es auch tut.',
    story: [
      'Mangan und ein wenig Eisen ergeben dieses Rosa, das je nach Licht in Grau kippt. Im Ofen entscheidet sich das erst in der letzten Stunde.',
      'Der Deckel sitzt mit einer halben Drehung fest und bleibt beim Ausgiessen, wo er ist.',
    ],
    details: ['Steinzeug, mattglasiert', '0,8 l', 'Sieb aus Steinzeug', 'Von Hand waschen'],
  },
  {
    id: 'vorrat',
    name: 'Vorrat',
    category: 'Objekte',
    price: 88,
    image: 'jar-terracotta-lid',
    alt: 'Terrakotta-Dose mit Deckel und eingeritzten Linien',
    lead: 'Unglasierte Terrakotta hält Salz trocken und Knoblauch dunkel.',
    story: [
      'Die Linien werden mit einer alten Schreinernadel eingeritzt, solange der Ton lederhart ist. Sie laufen absichtlich nicht ganz gerade.',
      'Der Deckel steht auf einem eigenen Teller, damit die Dose auch offen einen Platz hat.',
    ],
    details: ['Terrakotta, unglasiert', 'Höhe 14 cm', 'Mit Unterteller', 'Nicht spülmaschinenfest'],
  },
  {
    id: 'feldweg',
    name: 'Feldweg',
    category: 'Teller',
    price: 46,
    image: 'plate-pale-brushed',
    alt: 'Heller Teller mit grünen Pinselspuren auf Leinen',
    lead: 'Ein Pinselzug, der in der Mitte anfängt und nicht zurückkommt.',
    story: [
      'Die grünen Spuren sind Eisenoxid, mit einem breiten Pinsel in einer einzigen Bewegung aufgetragen. Wer zweimal ansetzt, fängt den Teller neu an.',
      'Der Rand bleibt unregelmässig — er erinnert daran, dass hier eine Hand im Spiel war.',
    ],
    details: ['Steinzeug, hell glasiert', 'Ø 22 cm', 'Stapelbar', 'Spülmaschinenfest'],
  },
  {
    id: 'duene',
    name: 'Düne',
    category: 'Sets',
    price: 180,
    image: 'vase-bowl-set-sand',
    alt: 'Sandfarbene Vase mit geschwungener Wand neben einer passenden Schale',
    lead: 'Vase und Schale aus derselben Charge Ton, gebrannt am selben Tag.',
    story: [
      'Die Wellen in der Wand entstehen von innen: Der Ton wird gegen die Hand gedrückt, bis er nachgibt, und dann in Ruhe gelassen.',
      'Vase und Schale gehören zusammen, weil sie denselben Ton und denselben Brand teilen. Man sieht es an der Farbe, sobald sie nebeneinander stehen.',
    ],
    details: ['Schamottierter Ton, unglasiert', 'Vase 24 cm, Schale Ø 16 cm', 'Set zu zwei Stücken', 'Vase innen versiegelt'],
  },
  {
    id: 'welle',
    name: 'Welle',
    category: 'Bad',
    price: 42,
    image: 'soap-dish-ridged',
    alt: 'Gesprenkelte Seifenschale mit gerillter Oberfläche',
    lead: 'Die Rillen laufen zur Kante, damit die Seife trocken bleibt.',
    story: [
      'Gerillt wird mit einem Holzkamm, in einem Zug quer über die noch weiche Platte. Das Wasser findet den Weg von selbst.',
      'Die Sprenkel kommen von grobem Schamott im Ton und treten stärker hervor, je öfter die Schale nass wird.',
    ],
    details: ['Steinzeug, teilglasiert', '13 × 9 cm', 'Ablauf zur Seite', 'Von Hand waschen'],
  },
  {
    id: 'kleine-sammlung',
    name: 'Kleine Sammlung',
    category: 'Sets',
    price: 240,
    image: 'collection-still-life',
    alt: 'Sechs kleine Keramikstücke: Becher, Schalen, Vasen und ein Löffel',
    lead: 'Sechs kleine Stücke aus sechs verschiedenen Bränden.',
    story: [
      'Am Ende jedes Brandes bleibt Platz für ein paar kleine Formen. Aus einem Jahr solcher Reste stellen wir diese Sammlung zusammen.',
      'Zwei Becher, zwei Schalen, eine Miniaturvase und ein Löffel — nie zweimal in derselben Kombination.',
    ],
    details: ['Steinzeug, gemischte Glasuren', 'Sechs Stücke', 'Zusammenstellung variiert', 'Von Hand waschen'],
  },
  {
    id: 'rahm',
    name: 'Rahm',
    category: 'Krüge',
    price: 64,
    image: 'pitcher-small-speckled',
    alt: 'Kleiner heller Krug mit gesprenkelter Glasur',
    lead: 'Klein genug für Rahm, gross genug für eine Handvoll Wiesenblumen.',
    story: [
      'Auf der Scheibe gedreht, dann am Ausguss mit dem Daumen geöffnet. Die Delle darunter ist die Stelle, an der das passiert ist.',
      'Die Glasur läuft am Bauch dünner aus und lässt den Ton durchscheinen.',
    ],
    details: ['Steinzeug, hell glasiert', '2 dl', 'Höhe 10 cm', 'Spülmaschinenfest'],
  },
  {
    id: 'kobalt-rost',
    name: 'Kobalt & Rost',
    category: 'Vasen',
    price: 165,
    image: 'vase-orange-blue',
    alt: 'Skulpturale Vase, zur Hälfte kobaltblau, zur Hälfte rostorange glasiert',
    lead: 'Zwei Glasuren, die sich in der Mitte nicht einigen.',
    story: [
      'Kobalt und Eisen vertragen sich im Ofen schlecht. Genau an der Naht, wo sie sich berühren, entsteht der schmale dunkle Rand.',
      'Von Hand aufgebaut und bewusst schief gelassen. Sie steht sicher, sieht aber nicht so aus.',
    ],
    details: ['Steinzeug, zweifarbig glasiert', 'Höhe 22 cm', 'Wasserdicht', 'Einzelstück'],
  },
  {
    id: 'glut',
    name: 'Glut',
    category: 'Objekte',
    price: 74,
    image: 'burner-essence-white',
    alt: 'Heller Duftbrenner mit Teelicht und zwei Grifföffnungen',
    lead: 'Ein Teelicht, eine Schale Wasser, ein paar Tropfen Öl.',
    story: [
      'Die Öffnungen an der Seite sind keine Dekoration: Sie führen die Wärme ab, damit die Schale oben nicht zu schnell kocht.',
      'Weiss glasiert, damit man sieht, wann es Zeit wird, ihn wieder auszuwaschen.',
    ],
    details: ['Steinzeug, weiss glasiert', 'Höhe 12 cm', 'Für Standard-Teelichter', 'Schale herausnehmbar'],
  },
];

/* Reihenfolge im Raster. Das Video steht an siebter Stelle: mitten im Bild,
   weit weg von der ersten Zelle und von der letzten Reihe. */
const GRID = [
  { type: 'product', id: 'schiefer' },
  { type: 'product', id: 'knoten' },
  { type: 'product', id: 'ascheglasur' },
  { type: 'product', id: 'wolkenrand' },
  { type: 'product', id: 'fuchsia' },
  { type: 'product', id: 'tropfen' },
  { type: 'video', id: 'knoten', src: 'vid/studio-wildflowers.mp4' },
  { type: 'product', id: 'nebelrose' },
  { type: 'product', id: 'vorrat' },
  { type: 'product', id: 'feldweg' },
  { type: 'product', id: 'duene' },
  { type: 'product', id: 'welle' },
  { type: 'product', id: 'kleine-sammlung' },
  { type: 'product', id: 'rahm' },
  { type: 'product', id: 'kobalt-rost' },
  { type: 'product', id: 'glut' },
];

function findProduct(id) {
  return PRODUCTS.find((p) => p.id === id) || null;
}
